### ISSUE TITLE
Setup/activate CI with travis

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#22]
Setup continuous integration with travis so that tests are run on every commit.

I started the .travis.yml, but travis integration for all branches must be activated.
@shalinshah1993 can you activate the travis support.
See here for information:
https://docs.travis-ci.com/user/getting-started/

**Comment by shalinshah1993** [comment]
So i created an account with travis and enabled continuous integration on the travis app. I see that you have already created a `.travis.yml` file. Do you want me to do anything else except sync on and travis app activation?

**Comment by matthiaskoenig** [comment]
Can you post the link to your travis account for the repository.
This should look something like 
https://travis-ci.org/shalinshah1993/sbscl
Here you should see that the continous integration is triggered for the repository and see that the build fails currently (from the next commit on after activation)

Basically this should look similar to 
https://travis-ci.org/matthiaskoenig/cy3sbml
but with failing builds right now.

Make sure that you activate all branches for travis.

**Comment by matthiaskoenig** [comment]
Just got the email notification for the failed build. So seems to work!
Link is here
https://travis-ci.org/shalinshah1993/SBSCL

Closing this. Now it is about writing/fixing tests.
