### ISSUE TITLE
Most tests are failing, tests and examples must be refactored

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#23]
Currently none of the tests is working for me (either failing or not discovered). 

The main reasons are 
- missing/incorrect file locations
- incorrect naming of test classes/functions
- mix of examples and tests! (test do not have a main function)

I will fix this. This will be major refactoring of the `src/test/` folder.

**Comment by shalinshah1993** [comment]
Yes they aren't working mainly because of the location (or hard links). 

Also, there are several other files in `src/test` which are sample files I used for test but they are not JUnit files so maven doesn't run them. They also need to be changed from `static main` classes to `JUnit`tests.

**Comment by matthiaskoenig** [comment]
Exactly. I will take care of this and write some additional tests.

**Comment by matthiaskoenig** [comment]
Did some initial work on this and could fix some issues. 
One major issue is loading resources from the maven repository. If in the SED-ML file a model is given via a relative file path than these cannot be resolved, because the file does not exist in the expected location. 
Feel free to tackle the failing tests, I will do some more work on this on the weekend.

**Comment by shalinshah1993** [comment]
I saw all the java files from examples folder are now in `src/main/java` https://github.com/shalinshah1993/SBSCL/commit/8c6ae3213d6470b962bd19a296815272bb8fc412. 

These are all the test classes that I originally used to test features in the library. I suggest after we convert them to JUnit tests, we move to `src/test/java`. What are your thoughts?

**Comment by draeger** [comment]
I assume @matthiaskoenig moved them to `examples` so that maven runs properly for now. I'd be happy if they could become additional JUnit test cases step by step and be moved back.

**Comment by matthiaskoenig** [comment]
There are test cases and examples. Everything with a main which can be run
with a main and external files is an example. Everything in junit Tests are
tests. Some of the examples will have corresponding unit tests, but should
not be removed.

**Comment by matthiaskoenig** [comment]
I fixed, what I could fix with the test cases. The remaining failing tests are all issues or bugs related either to SED-ML implementation or the LPsolver.

Closing this.
