### ISSUE TITLE
Deleting the dist folder

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#26]
Since we restructured SBSCL as per maven, all the binaries will be in target folder. Should we delete the `dist` folder where there is jar file?

**Comment by draeger** [comment]
Yes, this is no longer needed.

**Comment by shalinshah1993** [comment]
Fixed it in https://github.com/shalinshah1993/SBSCL/commit/09a1e9aa7288176d6d1d40d66e55b4efc7bd7e6a! Closing this issue.

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#26
