### ISSUE TITLE
Update uni-rostock maven dependencies

### ISSUE THREAD

**Issue by niko-rodrigue** [shalinshah1993/SBSCL#29]
See the end of the page https://sems.bio.informatik.uni-rostock.de/2013/10/maven-repository/:

> Update!
> As of January 2018 we’re now releasing our software through Maven central. We also switched the group id. It is now de.uni-rostock.sbi – so update your POMs. But don’t worry, you don’t need to update all the package names, the classes are still packaged as de.unirostock.sems.*. Find our artifacts published under de.uni-rostock.sbi at Maven Central.
> 
> Moreover, our Maven repository has moved to mvn.bio.informatik.uni-rostock.de (we installed an HTTP redirect for the former URL).
> However, since we’re now releasing through Maven Central there is no need to integrate our 3rd-party server anymore. So forget about the snippet above and just update the group ids of our tools ;-)

So we need to update our pom files to remove their repo and change the group ids for their dependencies.

**Comment by matthiaskoenig** [comment]
The artefact in the pom.xml is already the correct one. I just cleaned my maven repository and have no problem installing, i.e., no certificate issues for me.

**Comment by niko-rodrigue** [comment]
The problem come from BFLog which is present both in Maven central and on the uni-rostock with the same group id.

To avoid any problem, we just need to remove the uni-rostock repository from the pom file as it is not needed any more:

```
diff --git a/pom.xml b/pom.xml
index 3a3c777..9b62536 100644
--- a/pom.xml
+++ b/pom.xml
@@ -153,16 +153,6 @@
                <name>The JSBML Snapshot repository</name>
                <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
        </repository>
-       <!-- Adding repository to download CombineArchive -->
-       <repository>
-               <id>sems-maven-repository-releases</id>
-               <name>SEMS Maven Repo</name>
-               <url>http://mvn.sems.uni-rostock.de/releases/</url>
-               <layout>default</layout>
-               <snapshots>
-                       <enabled>false</enabled>
-               </snapshots>
-       </repository>
   </repositories>
 
   <!-- =================================================================== -->


```

**Comment by matthiaskoenig** [comment]
Removing the SEMS repository results in 
```
[ERROR] Failed to execute goal on project sbscl: Could not resolve dependencies for project org.simulator:sbscl:jar:1.5: Could not find artifact de.binfalse:BFLog:jar:1.3.3 in in-project (file:/home/mkoenig/git/sbscl-shalin/src/lib/maven) -> [Help 1]
```
If you clean your repository everything should work, i.e. remove .m2/repository/*.

In the current configuration with the SEMS repo things work locally for me and also in travis CI (which is doing a clean install).
@niko-rodrigue Could you check if the current `working-branch` works for you with a clean maven repository?

**Comment by niko-rodrigue** [comment]
Let's forget about it, I thought that BFLog was in maven central, it is there but not the version 1.3.3 that the combineArchive depend on ! I will close this issue as it is probably only a problem for me on my limited centos 7 distrib. And I have found a work around so all good.

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#24
