### ISSUE TITLE
SED-ML FileResolver is broken

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#32]
It seems to me that the SED-ML file resolver is not working correctly. When trying to resolve relative URIs for models it resolves them relative to the current working directory, but it should resolve relative to the SED-ML absolute path!

This breaks the following test, which relies on a model `abc_1.xml` located next to the SED-ML file `sed1.xml`. 

```
@Test
public final void testBasicSEDMLExecutorForLocalFile() throws XMLException, IOException 
```

**Comment by shalinshah1993** [comment]
Yes, I agree. It is only working with SED-ML files where sbml model paths are marium URI's.

**Comment by shalinshah1993** [comment]
I checked the code, it seems like `jlibsedml` issue. Our code already has FileModelResolver added in the code whose `getModelXMLFor()` method should check for the model in the current directory. Can you please point out this issue to Richard Adams or someone else from jlibsedml? I am unable to find their GitHub page and their SourceForge page has disabled create a ticket for bugs.

**Comment by matthiaskoenig** [comment]
I commited a fix for this. Currently the SED-ML executor is initialized with a sedml object. Because this object has no knowledge about the base directory the file was in the models with relative paths could not work. 
One needs to provide the base directory of the sedml file which is than used to resolve model files with relative paths.

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#22
