### ISSUE TITLE
Support for hierarchically structured models (comp package) - map submodel ids

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#4]
Add support for simulating hierarchical models consisting of multiple sub-models. Since the SBML comp package is defined such that a hierarchical model can be “flattened” to an equivalent, the non-hierarchical version that uses only plain SBML constructs, the implementation will flatten the structure using JSBML flattening routine.

**Comment by matthiaskoenig** [comment]
As part of the flattening routine the ids of objects are changing. One question is if there should be an option to return individual MultiTables for the individual submodels (i.e. doing an unflattening of the results again so that they match to the submodels and return one MultiTable for every submodel). This should also be trivial, because you can just map the ids back to the submodels.

**Comment by shalinshah1993** [comment]
I was thinking more about this problem and realized there is not much work here. I added one JAVA example to show how to convert an SBML file with hierarchical models [here](https://github.com/shalinshah1993/SBSCL/blob/working-branch/examples/org/simulator/CompExample.java). Once the SBML file is flattened, the output MultiTable generated will automatically be merged.

What else do you recommend doing here?

**Comment by draeger** [comment]
Something is not entirely clear to me: in this example I don't see where the ids are mapped back to the old ones. @shalinshah1993, could you please help me seing it by point this out? It is probably very obivious, so sorry for asking such a trivial quesiton.

**Comment by shalinshah1993** [comment]
I think I didn't do that. All I did was flatten model and run it.

**Comment by matthiaskoenig** [comment]
@shalinshah1993 Like I mentioned it would be great to be able to map back to the original comp models. For instance, one wants to visualize the simulation results within the respective comp submodel.

**Comment by shalinshah1993** [comment]
I agree! It seems that what I am looking for is `ListOfModels` as the output of the flattening routine `CompFlatteningConverter`. However, I don't think that is happening. Currently, I am referring to think commit https://github.com/sbmlteam/jsbml/commit/46ca561edbca85a1f05f14dcc6e08acd65b2e235 to understand what it does.

However, this documentation for the class says - `Public method to call on a CompflatteningConverter object. Takes a SBML Document and flattens the models of the comp plugin. Returns the SBML Document with a flattend model`. However on SBML specification I see that only one model per SBML file is allowed. Something is off or I am not understanding it correctly

**Comment by draeger** [comment]
I guess this is more a JSBML issue than SBSCL. We should stipulate that the flattening routine may use the `userObject` hash to memorize the original `id` before modifying it.

Thinking about it, we could also recursively traverse the entire JSBML data structure. If an object has an `ID` we can just save it in the `userObject` hash. Afterwards we call flattening and obtain the result that till has all the original `ID`s.

**Comment by shalinshah1993** [comment]
Please refer to the map process. I recursively went through original JSBML object to map submodel id to Stack<Submodels>. Confirm it and then I will close this issue and feature!

https://github.com/shalinshah1993/SBSCL/blob/2634538609e31f2f707de4656a0ba91c09766821/examples/org/simulator/CompExample.java#L94

**Comment by draeger** [comment]
I left a comment at https://github.com/shalinshah1993/SBSCL/commit/2634538609e31f2f707de4656a0ba91c09766821 about the class `MapIdToModels`.

**Comment by shalinshah1993** [comment]
Based on our discussion [here](https://github.com/shalinshah1993/SBSCL/commit/2634538609e31f2f707de4656a0ba91c09766821#commitcomment-29169421), I have updated remapping of `Id` to `TreeNode`.

https://github.com/shalinshah1993/SBSCL/blob/27b20fb12a9ec1d8d31b1638fcbe1c605abc1f0e/examples/org/simulator/CompExample.java#L81

https://github.com/shalinshah1993/SBSCL/blob/27b20fb12a9ec1d8d31b1638fcbe1c605abc1f0e/examples/org/simulator/CompExample.java#L104

**Comment by draeger** [comment]
Please see my comment at https://github.com/shalinshah1993/SBSCL/commit/27b20fb12a9ec1d8d31b1638fcbe1c605abc1f0e.

**Comment by shalinshah1993** [comment]
Please check my final commit. https://github.com/shalinshah1993/SBSCL/commit/bf8579be1c14671680d1cc373aaa98e73ebe17d7

1) Removed `GetMetaInfo` class since jSBML has `getElementById`
2) Updated recursive method to remove redundancy. 

Confirm the changes and then I will close this issue.
