### ISSUE TITLE
Number of points in SED-ML simulations incorrect

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#44]
There must be an additional point in the time course simulations. This is some madness the original SED-ML editors thought of and everybody implements incorrectly.

>The  attribute numberOfPoints of  type integer describes  the  number  of  points  expected  in  the  result.   Software  interpreting  the uniformTimeCourse is expected to produce a first outputPoint at time outputStartTime and then numberOfPoints output points with the results of the simulation.  Thus a total of numberOfPoints + 1 output points will be produced.

**Comment by shalinshah1993** [comment]
Fixed this https://github.com/shalinshah1993/SBSCL/commit/08fa9608fa3d54513b7a27b2a2c56ee1d8c7447b

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#17
