### ISSUE TITLE
Move the assembly file to the source folder

### ISSUE THREAD

**Issue by draeger** [shalinshah1993/SBSCL#48]
The file `assembly.xml` should not be located in the project's root directory, but in `src/assembly`. Please make sure it is used during the build process by the `pom.xml` file.

**Comment by matthiaskoenig** [comment]
What is the `assembly.xml` for? Never saw this before?

**Comment by draeger** [comment]
Maven's assembly plugin can use the description in this file for more complex build processes when executing the `package` process. See the description [here](https://maven.apache.org/guides/mini/guide-assemblies.html).

**Comment by shalinshah1993** [comment]
Fixed this. https://github.com/shalinshah1993/SBSCL/commit/53128fbffd5435aeb57a7e0e436c54fd78f441b2

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#16
