### ISSUE TITLE
Cannot reach steadyState for repeated-steady-scan-oscli test

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#52]
On running this test, simulation-core cannot find a steadyState solution.

```
03.07 10:38:11 WARNS org.simulator.sedml.SedMLSBMLSimulatorExecutor@202: Required algorithm is not supported. Finding closest available match...
03.07 10:38:13 WARNS org.simulator.sedml.SedMLSBMLSimulatorExecutor@223: Running using KISAO:0000033 Rosenbrock method
Jul 03, 2018 10:53:38 AM org.simulator.math.odes.AbstractDESSolver steadystate
WARNING: Steady state could not be reached!
```

**Comment by matthiaskoenig** [comment]
@shalinshah1993 Did you look at the timecourses of the solution? I assume in the test the steady state is not run long enough (this is one of the problems with steady state calculation based on time course integration). It strongly depends on the time scale of the model what is the right time for the time course steady state calculation. 
Perhaps it would make sense to set the time for steady state calculation based on the actual changes which are observed in some prelimanary integration.

**Comment by shalinshah1993** [comment]
So by default, we run for 1e3 time steps. Every time a steadyState is not found we increase logarithmically this time step. Currently, the default value of maxSteps is 10 which means we can take upto 1e13 time steps before announcing steadyState is not reached.

**Comment by matthiaskoenig** [comment]
Did you look at the timecourses for 1e13 steps? Are they approaching steady state? I.e. are the species approximating some constant values?

**Comment by shalinshah1993** [comment]
It seems there was a bug in steadyState simulation solver. There was no difference between curState and nextState variable prior to comparing them. Now, the test is actually reaching steadyState without any warnings. Check this commit!

https://github.com/shalinshah1993/SBSCL/commit/52a5134f3e90070823f2218e9ed7601e294e565c

**Comment by draeger** [comment]
I think, on the long term, it would be better to implement a more efficient steady-state analysis based on matrix operations. Should we add this as a feature request that we can expect to sit there for quite some time?

**Comment by matthiaskoenig** [comment]
Yes. Sounds like a good plan. It is clear that the current solution is a
pragmatic one, in the long run a new steady state solver should be
provided, but definitely not as part of rhis gsoc.

**Comment by shalinshah1993** [comment]
Yes, there has to be a better to do this. It should be much easier and faster simply if we can find a Java-based library similar to the python libraries that can implement NLEQ. 

Closing this issue!

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#12
