### ISSUE TITLE
Remove org.simulator.examples folder

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#54]
Currently, the simulation library has some redundant code. All the early examples implemented to test features are in `org.simulator.examples` folder. However, they are redundant now since similar JUnit tests exist in `src/test/java` folder.

**Comment by matthiaskoenig** [comment]
Please don't remove this. Yes, some of the code is redundant, but the two things serve very different purposes.
The example folder shows user how they can use the SBSCL in their JAVA code. Whereas the junit tests test the code and ensure that the core functionality works.

**Comment by shalinshah1993** [comment]
Thanks for confirming. Closing this!

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#11
