### ISSUE TITLE
Update index.html and wiki

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#57]
The index page and Github wiki for simulation core have to be updated.

**Comment by shalinshah1993** [comment]
@draeger do we update these now or during the new release of SBSCL?

**Comment by draeger** [comment]
It would be best if there were a folder `src/site` where we could add the web resources directly in this project. The old page at SourceForge should be removed.

**Comment by shalinshah1993** [comment]
This has been updated. New webpage can be found here -  https://draeger-lab.github.io/SBSCL

The SourceForge page is deprecated and will be deleted soon.

**Comment by shalinshah1993** [comment]
This issue was moved to draeger-lab/SBSCL#9
