### ISSUE TITLE
FBA gives incorrect objective_value 0 for bigg models iMM1415 & iRC1080

### ISSUE THREAD

**Issue by matthiaskoenig** [shalinshah1993/SBSCL#59]
see https://github.com/draeger-lab/SBSCL/issues/1

When comparing the results of simple FBA simulations of cobrapy with SBSCL the following two BiGG models give different results:
```
objective_value_cobrapy 	mid 	objective_value_sbscl 	identical
1.3634279056507832 	iMM1415 	0.0 	False
6.156851475936173 	iRC1080 	0.0 	False
```

**Comment by shalinshah1993** [comment]
Discussion can be done here - https://github.com/draeger-lab/SBSCL/issues/1
