### ISSUE TITLE
Restructure SBSCL project directory

### ISSUE THREAD

**Issue by shalinshah1993** [shalinshah1993/SBSCL#7]
Originally, SBSCL used ant script for build process which was replaced recently by maven. Currently, eclipse plugin m2e is used for build process. This needs to be changed to maven build which requires project directory restructuring to follow eclipse maven standards.

**Comment by shalinshah1993** [comment]
Closing this issue! Restructuring can be found in this commit -> 
https://github.com/shalinshah1993/SBSCL/commit/cbb9c16171464a4263e203ca72fe6d2bc6ee7fb5

https://github.com/shalinshah1993/SBSCL/commit/76d97da7f63bbba9fb1350ca6a0c020fb6a13030

Some of the test right now are JUnit test and the rest I will update later.

@draeger @matthiaskoenig

**Comment by matthiaskoenig** [comment]
I am happy with the restructuring for now. Only tests/examples have to be updated. This is part of #23. Closing this issue.
